FROM grokloc/grokloc-perl5:dev
WORKDIR /grokloc
ENV PERL5LIB "/grokloc/lib:/grokloc/service/app/lib"
ENV PERLCRITIC /grokloc/.perlcritic
ENV PERL_JSON_BACKEND "Cpanel::JSON::XS,JSON::XS,JSON::PP"
ENV GROKLOC_ENV "UNIT"
COPY env env
COPY lib lib
COPY service service
COPY t t
COPY Makefile Makefile
COPY .perlcritic .perlcritic
CMD ["tail", "-f", "/dev/null"]
