version: 2
jobs:
  build:
    docker:
      - image: grokloc/grokloc-perl5:unit
    environment:
      PERL5LIB: "/grokloc/lib:/grokloc/service/app/lib"
      PERLCRITIC: "/grokloc/.perlcritic"
      PERL_JSON_BACKEND: "Cpanel::JSON::XS,JSON::XS,JSON::PP"
      CHECKOUT_PATH: "/__w/grokloc-perl5/grokloc-perl5"
      GROKLOC_ENV: "UNIT"      
      APP_HOST: "localhost"
      APP_PORT: "3000"
      CI: "1"
    working_directory: /grokloc
    steps:
      - checkout
      - run: make local-check
      - run: make local-test
      - run: make local-critic
