name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: grokloc/grokloc-perl5:ci
      env:
        PERL5LIB: "/__w/grokloc-perl5/grokloc-perl5/lib:/__w/grokloc-perl5/grokloc-perl5/service/app/lib"
        PERLCRITIC: "/__w/grokloc-perl5/grokloc-perl5/.perlcritic"
        PERL_JSON_BACKEND: "Cpanel::JSON::XS,JSON::XS,JSON::PP"
        CHECKOUT_PATH: "/__w/grokloc-perl5/grokloc-perl5"
        GROKLOC_ENV: "UNIT"
        APP_HOST: "localhost"
        APP_PORT: "3000"
        ROOT_ORG: "893005f5-f8aa-4a8c-9535-df3210e78d75"
        ROOT_USER: "aa244ac4-466a-427c-bf77-742f5f918469"
        CI: "1"
    steps:
      - uses: actions/checkout@v2
      - run: make ci-check
      - run: make ci-test
      - run: make ci-critic
