name: compose
on: [push]
jobs:
  compose:
    runs-on: ubuntu-latest
    env:
      CI: "1"
    steps:
      - uses: actions/checkout@v2
      - name: compose version
        run: docker-compose --version
      - name: compose up
        run: docker-compose up -d
